model_provider = "openrouter"
model_reasoning_effort = "high"
model = "openai/gpt-5-mini"

[model_providers.openrouter]
name = "openrouter"
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENROUTER_API_KEY"

[projects."/workspace/repos/6b9ee6f4-0084-41d3-84ff-eb4b63dc8fcc"]
trust_level = "trusted"
