import json
from pathlib import Path

from app.command_runner import CommandRunner


class GitHubClient:
    def __init__(self, command_runner: CommandRunner, gh_command: str, timeout_seconds: int) -> None:
        self._runner = command_runner
        self._gh = gh_command
        self._timeout = timeout_seconds

    def create_pr(
        self,
        repo_path: Path,
        branch: str,
        base_branch: str,
        run_id: str,
        title: str | None = None,
        body: str | None = None,
    ) -> str:
        result = self._runner.run(
            [
                self._gh,
                "pr",
                "create",
                "--title",
                title or f"Add AI-generated tests for run {run_id}",
                "--body",
                body or f"Generated by the AI test generation pipeline for run {run_id}.",
                "--base",
                base_branch,
                "--head",
                branch,
            ],
            cwd=repo_path,
            timeout_seconds=self._timeout,
        )
        if result.exit_code != 0:
            raise RuntimeError(result.stderr or result.stdout or "gh pr create failed")
        return result.stdout.strip()

    def get_pr_changed_files(self, repository_full_name: str, pr_number: int) -> list[str]:
        result = self._runner.run(
            [
                self._gh,
                "pr",
                "view",
                str(pr_number),
                "--repo",
                repository_full_name,
                "--json",
                "files",
            ],
            timeout_seconds=self._timeout,
        )
        if result.exit_code != 0:
            raise RuntimeError(result.stderr or result.stdout or "gh pr view failed")
        payload = json.loads(result.stdout)
        return [file["path"] for file in payload.get("files", [])]

    def get_pr_checks(self, repo_path: Path, branch: str) -> str:
        result = self._runner.run(
            [
                self._gh,
                "pr",
                "checks",
                branch,
                "--json",
                "name,state,conclusion,link",
            ],
            cwd=repo_path,
            timeout_seconds=self._timeout,
        )
        if result.exit_code != 0:
            return result.stderr or result.stdout or "gh pr checks failed"
        return result.stdout.strip()
