from pathlib import Path

from app.command_runner import CommandRunner


class GitHubClient:
    def __init__(self, command_runner: CommandRunner, gh_command: str, timeout_seconds: int) -> None:
        self._runner = command_runner
        self._gh = gh_command
        self._timeout = timeout_seconds

    def create_pr(self, repo_path: Path, branch: str, base_branch: str, run_id: str) -> str:
        result = self._runner.run(
            [
                self._gh,
                "pr",
                "create",
                "--title",
                f"Add AI-generated tests for run {run_id}",
                "--body",
                f"Generated by the AI test generation pipeline for run {run_id}.",
                "--base",
                base_branch,
                "--head",
                branch,
            ],
            cwd=repo_path,
            timeout_seconds=self._timeout,
        )
        if result.exit_code != 0:
            raise RuntimeError(result.stderr or result.stdout or "gh pr create failed")
        return result.stdout.strip()
